"""MongoDB Constants"""

from enum import IntEnum

# Read preferences (MongoDB)
READ_PREFERENCE_PRIMARY = "primary"
READ_PREFERENCE_PRIMARY_PREFERRED = "primaryPreferred"
READ_PREFERENCE_SECONDARY = "secondary"
READ_PREFERENCE_SECONDARY_PREFERRED = "secondaryPreferred"
READ_PREFERENCE_NEAREST = "nearest"

# Default read preference
DEFAULT_READ_PREFERENCE = READ_PREFERENCE_PRIMARY

# Write concern levels
WRITE_CONCERN_UNACKNOWLEDGED = 0
WRITE_CONCERN_ACKNOWLEDGED = 1
WRITE_CONCERN_MAJORITY = "majority"

# Default write concern
DEFAULT_WRITE_CONCERN = WRITE_CONCERN_ACKNOWLEDGED

# Read concern levels
READ_CONCERN_LOCAL = "local"
READ_CONCERN_MAJORITY = "majority"
READ_CONCERN_LINEARIZABLE = "linearizable"
READ_CONCERN_AVAILABLE = "available"
READ_CONCERN_SNAPSHOT = "snapshot"

# Default read concern
DEFAULT_READ_CONCERN = READ_CONCERN_LOCAL

# Connection parameters
DEFAULT_PORT = 27017
DEFAULT_HOST = "localhost"
DEFAULT_DATABASE = "test"

# Thread safety
class ThreadSafety(IntEnum):
    """Thread safety levels"""
    NOT_THREADSAFE = 0
    THREADSAFE = 1
    SERIALIZED = 3


THREADSAFETY = ThreadSafety.THREADSAFE  # MongoDB connections are thread-safe

# Connection pool defaults
DEFAULT_MIN_CONNECTIONS = 1
DEFAULT_MAX_CONNECTIONS = 100
DEFAULT_CONNECTION_TIMEOUT = 20.0
DEFAULT_SERVER_SELECTION_TIMEOUT = 30.0
DEFAULT_SOCKET_TIMEOUT = None

# Write concern options
DEFAULT_W_TIMEOUT = None
DEFAULT_JOURNAL = None

# BSON types
BSON_TYPE_DOUBLE = 1
BSON_TYPE_STRING = 2
BSON_TYPE_DOCUMENT = 3
BSON_TYPE_ARRAY = 4
BSON_TYPE_BINARY = 5
BSON_TYPE_UNDEFINED = 6
BSON_TYPE_OBJECT_ID = 7
BSON_TYPE_BOOLEAN = 8
BSON_TYPE_DATE_TIME = 9
BSON_TYPE_NULL = 10
BSON_TYPE_REGEX = 11
BSON_TYPE_DBPOINTER = 12
BSON_TYPE_JAVASCRIPT = 13
BSON_TYPE_SYMBOL = 14
BSON_TYPE_JAVASCRIPT_WITH_SCOPE = 15
BSON_TYPE_INT32 = 16
BSON_TYPE_TIMESTAMP = 17
BSON_TYPE_INT64 = 18
BSON_TYPE_DECIMAL128 = 19
BSON_TYPE_MIN_KEY = 255
BSON_TYPE_MAX_KEY = 127

